---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-latest

suites:
  - name: default
    run_list:
      - recipe[mariadb::server]
      - recipe[icinga2]
    attributes:

driver_config:
  forward:
    - 80
  hostname: icinga2.box
  dockerfile: Dockerfile
  run_command: /sbin/init
  privileged: true
