---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: centos-latest

suites:
  - name: default
    run_list:
      - recipe[mariadb::server]
      - recipe[icinga2]
      - recipe[icinga2::client]
    attributes: 
#{ icinga2: { client: { host_group: { short: , desc: "Some desc" } } } }

driver_config:
  forward:
    - 80
  hostname: icinga2.box
  dockerfile: Dockerfile
  run_command: /sbin/init
  privileged: true
